name: ZJEMC_Realtime_Update

on:
  # schedule:
    # - cron: "45 * * * *"   # 每小时执行一次
  workflow_dispatch:
permissions:
  contents: write
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉代码
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ 安装 Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ 安装依赖（关键）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests

      # 4️⃣ 安装 Chrome + driver（关键）
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # 5️⃣ 运行脚本
      - name: Run crawler
        run: |
          python crawler.py
